/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "my_led.h"
#include "ext_intr.h"

/*
 * Global software flag shared between
 * main() and EXTI interrupt service routine
 *
 * MUST be declared volatile because:
 * - It is modified inside an ISR
 * - It is read inside main()
 */
volatile uint8_t exti0_flag = 0;

int main(void)
{
    led_init();        // Initialize LED
    extint_init();     // Initialize EXTI0

    while (1)
    {
        /*
         * Check if interrupt has occurred
         */
        if (exti0_flag == 1)
        {
            led_toggle(14);   // Toggle LED in main context
            exti0_flag = 0;   // Clear software flag
        }

        /* Other background tasks can run here */
    }
}







